name: Setup Gradle
description: Set up Gradle with caching and encryption

runs:
  using: composite
  steps:
    - name: Setup Gradle
      uses: gradle/actions/setup-gradle@3f131e8634966bd73d06cc69884922b02e6faf92 # v6
      with:
        add-job-summary: on-failure
        cache-encryption-key: ${{ env.GRADLE_ENCRYPTION_KEY }}
