name: Report Build Results
description: Publish build report annotations

runs:
  using: composite
  steps:
    - name: Report build results
      uses: gmazzo/publish-report-annotations@fd89066243de4fee389751007d98b4ac1d6ffeb0 # v1.22.3
      if: ${{ !cancelled() }}
      with:
        filterPassedTests: true
        invalidFileAction: report
