name: Report Build Results
description: Publish build report annotations

runs:
  using: composite
  steps:
    - name: Report build results
      uses: gmazzo/publish-report-annotations@d9c7375f4c587879eeedba56c6e35f1235219f9f # v1
      if: ${{ !cancelled() }}
      with:
        filterPassedTests: true
        invalidFileAction: report
