name: Report Build Results
description: Publish build report annotations

runs:
  using: composite
  steps:
    - name: Report build results
      uses: gmazzo/publish-report-annotations@29468df7af4b92ce93708c9f30af13a88d057387 # v1
      if: ${{ !cancelled() }}
      with:
        filterPassedTests: true
        invalidFileAction: report
