[versions]
blueprint = "2.1.0"
junit = "6.0.2"

[libraries]
assertk = { module = "com.willowtreeapps.assertk:assertk", version = "0.28.1" }
blueprintAssertk = { module = "dev.jonpoulton.blueprint:test-assertk", version.ref = "blueprint" }
junit-api = { module = "org.junit.jupiter:junit-jupiter-api", version.ref = "junit" }
junit-launcher = { module = "org.junit.platform:junit-platform-launcher" }
ktfmt = { module = "com.facebook:ktfmt", version = "0.61" } # only used in ktfmt.sh

[plugins]
buildconfig = { id = "com.github.gmazzo.buildconfig", version = "6.0.7" }
blueprint-core = { id = "dev.jonpoulton.blueprint", version.ref = "blueprint" }
blueprint-test = { id = "dev.jonpoulton.blueprint.test", version.ref = "blueprint" }
detekt = { id = "dev.detekt", version = "2.0.0-alpha.2" }
dokka = { id = "org.jetbrains.dokka", version = "2.1.0" }
kotlin = { id = "org.jetbrains.kotlin.jvm", version = "2.2.0" }
licensee = { id = "app.cash.licensee", version = "1.14.1" }
publish = { id = "com.vanniktech.maven.publish", version = "0.35.0" }
publishReport = { id = "io.github.gmazzo.publications.report", version = "1.3.3" }
