name: Setup Java
description: Set up Zulu JDK from .java-version

runs:
  using: composite
  steps:
    - name: Setup JDK
      uses: actions/setup-java@b6effb05e454b25005698d916606bdc6ffcbf961 # v5.7.0
      with:
        java-version-file: .java-version
        distribution: zulu
