name: Setup Java
description: Set up Zulu JDK from .java-version

runs:
  using: composite
  steps:
    - name: Setup JDK
      uses: actions/setup-java@03ad4de0992f5dab5e18fcb136590ce7c4a0ac95 # v5
      with:
        java-version-file: .java-version
        distribution: zulu
