---
complexity:
  LabeledExpression:
    active: false

comments:
  active: false

naming:
  FunctionNameMaxLength:
    excludes: ['**/test/**']
  NonBooleanPropertyPrefixedWithIs:
    allowSingleTypedGenerics: true

style:
  MultilineRawStringIndentation:
    active: false
  RedundantVisibilityModifier:
    active: false
