---
complexity:
  LabeledExpression:
    active: false
  LongParameterList:
    allowedFunctionParameters: 7

comments:
  active: false

naming:
  FunctionNameMaxLength:
    excludes: ['**/test/**']
  NonBooleanPropertyPrefixedWithIs:
    allowSingleTypedGenerics: true

style:
  LoopWithTooManyJumpStatements:
    maxJumpCount: 2
  MultilineRawStringIndentation:
    active: false
  RedundantVisibilityModifier:
    active: false
  ReturnCount:
    max: 3
