name: Publish snapshot

on:
  push:
    branches: [ "main" ]
  workflow_dispatch:

permissions:
  contents: write
  checks: write

env:
  GRADLE_ENCRYPTION_KEY: ${{ secrets.GRADLE_ENCRYPTION_KEY }}

# This ensures publish jobs run sequentially instead of in parallel
concurrency:
  group: publish
  cancel-in-progress: false

jobs:
  publish-snapshot:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@df4cb1c069e1874edd31b4311f1884172cec0e10 # v6
        with:
          fetch-depth: 0
          fetch-tags: true
      - uses: ./.github/actions/setup-java
      - uses: ./.github/actions/setup-gradle
      - uses: ./.github/actions/setup-gradle-properties

      - name: Get version
        id: version
        run: |
          GRADLE_VERSION="$(grep VERSION_NAME gradle.properties | cut -d "=" -f 2)"
          echo "GRADLE_VERSION=$GRADLE_VERSION"
          echo "value=$GRADLE_VERSION" >> "$GITHUB_OUTPUT"

      - name: Publish snapshot
        if: |
          github.repository == 'jonapoul/straitjacket' &&
          github.ref == 'refs/heads/main' &&
          contains(steps.version.outputs.value, '-SNAPSHOT')
        env:
          ORG_GRADLE_PROJECT_mavenCentralUsername: ${{ secrets.SONATYPE_USERNAME }}
          ORG_GRADLE_PROJECT_mavenCentralPassword: ${{ secrets.SONATYPE_PASSWORD }}
          ORG_GRADLE_PROJECT_signingInMemoryKey: ${{ secrets.GPG_IN_MEMORY_KEY }}
          ORG_GRADLE_PROJECT_signingInMemoryKeyPassword: ${{ secrets.GPG_KEY_PASSWORD }}
        run: ./gradlew publishToMavenCentral -x dokkaGeneratePublicationHtml --no-configuration-cache
